instructions = [
	"MATH_ADDITION",
	"MATH_SUBTRACT",
	"MATH_MULTIPLY",
	"MATH_DIVISION",
	"MATH_MODULUS",
	"MATH_SHIFT_LEFT",
	"MATH_SHIFT_RIGHT",
	"MATH_EQUAL",
	"MATH_NOT_EQUAL",
	"MATH_LESS_THAN_EQUAL",
	"MATH_GREATER_THAN_EQUAL",
	"MATH_LESS_THAN",
	"MATH_GREATER_THAN",
	"MATH_BITWISE_AND",
	"MATH_BITWISE_OR",
	"MATH_BITWISE_XOR",
	"MATH_STRING_EQUAL",
	"MATH_STRING_NOT_EQUAL",
	"MATH_APPEND",
	"MATH_SPC",
	"MATH_TAB",
	"MATH_NL",
]

def get_math_instructions():
	return instructions